export * from './articles1';
export * from './articles2';
export * from './articles3';
export * from './articles4';
export * from './blogposts';
export * from './article';
export * from './tahminScreen';
export * from './matchDetailScreen';
export * from './anasayfa';